import { ref } from 'vue';

export const tagButtons = [
    { value: "bitcoin", label: "Bitcoin" },
    { value: "ethereum", label: "Ethereum" },
    { value: "solana", label: "Solana" },
    { value: "meme", label: "Meme" },
    { value: "defi", label: "DeFi" },
    { value: "nft", label: "NFT" },
    { value: "web3", label: "Web3" },
    { value: "ai", label: "AI" },
];

export const leftList = [
    {
        avatar: "https://picsum.photos/seed/user1/40/40",
        title: "鲍威尔：美联储在2025年11月18日至20日会议会宣布降息2%？",
        percentage: "75%",
        amount: "19.00",
        yesCount: 1234,
        noCount: 567,
        isFavorite: false,
        maxLeverage: "10X",
        maxReturn: "182%",
        timeRemaining: "04:30:57",
        participantCount: 1280,
        isTimeUrgent: false,
    },
    {
        avatar: "https://picsum.photos/seed/user2/40/40",
        title: "鲍威尔：美联储在2025年11月18日至20日会议会宣布降息2%？",
        percentage: "25%",
        amount: "19.00",
        yesCount: 1234,
        noCount: 567,
        isFavorite: false,
        maxLeverage: "10X",
        maxReturn: "182%",
        timeRemaining: "02:15:30",
        participantCount: 1280,
        isTimeUrgent: true,
    },
    {
        avatar: "https://picsum.photos/seed/user3/40/40",
        title: "鲍威尔：美联储在2025年11月18日至20日会议会宣布降息2%？",
        percentage: "50%",
        amount: "19.00",
        yesCount: 1234,
        noCount: 567,
        isFavorite: false,
        maxLeverage: "10X",
        maxReturn: "182%",
        timeRemaining: "12:45:20",
        participantCount: 1280,
        isTimeUrgent: false,
    },
    {
        avatar: "https://picsum.photos/seed/user4/40/40",
        title: "鲍威尔：美联储在2025年11月18日至20日会议会宣布降息2%？",
        percentage: "90%",
        amount: "19.00",
        yesCount: 1234,
        noCount: 567,
        isFavorite: false,
        maxLeverage: "10X",
        maxReturn: "182%",
        timeRemaining: "01:20:10",
        participantCount: 1280,
        isTimeUrgent: true,
    },
    {
        avatar: "https://picsum.photos/seed/user5/40/40",
        title: "鲍威尔：美联储在2025年11月18日至20日会议会宣布降息2%？",
        percentage: "33%",
        amount: "19.00",
        yesCount: 1234,
        noCount: 567,
        isFavorite: false,
        maxLeverage: "10X",
        maxReturn: "182%",
        timeRemaining: "08:15:45",
        participantCount: 1280,
        isTimeUrgent: false,
    },
];

const createRightListItem = (seed, title = "美联储12月会做出决定吗？") => ({
    avatar: `https://picsum.photos/seed/user${seed}/40/40`,
    title,
    percentage: "14%",
    amount: "19.00",
    isFavorite: false,
    maxLeverage: "10X",
    maxReturn: "182%",
    timeRemaining: "04:30:57",
    participantCount: 1280,
    isTimeUrgent: false,
    options: [
        { text: "下调50个基点以上", percentage: "2%", yesCount: 123, noCount: 456 },
        { text: "增长超过25基点", percentage: "32%", yesCount: 789, noCount: 101 },
    ],
});

export const rightList = Array.from({ length: 20 }, (_, index) => createRightListItem(6 + index));
