export const tagButtons = [
    { value: 'bitcoin', label: 'Bitcoin' },
    { value: 'ethereum', label: 'Ethereum' },
    { value: 'solana', label: 'Solana' },
    { value: 'meme', label: 'Meme' },
    { value: 'defi', label: 'DeFi' },
    { value: 'nft', label: 'NFT' },
    { value: 'web3', label: 'Web3' },
    { value: 'ai', label: 'AI' },
];

/**
 * 首页主列表数据（单一数据源）
 * 通过 cardType: 'large' | 'small' 控制展示大卡片或小卡片
 */
export const cardList = [
    // 大卡片：宏观 / 加密大事件
    {
        id: 'btc-halving-2025-high',
        cardType: 'large',
        avatar: 'https://picsum.photos/seed/btc1/40/40',
        title: '比特币在 2025 年减半后 30 天内会创下历史新高吗？',
        percentage: '68%',
        amount: '250,430',
        yesCount: 4213,
        noCount: 1968,
        isFavorite: false,
        maxLeverage: '10X',
        maxReturn: '230%',
        timeRemaining: '03:12:45',
        participantCount: 5875,
        isTimeUrgent: true,
    },

    // 小卡片：更细分的价格/区间预测
    {
        id: 'btc-range-weekend',
        cardType: 'small',
        avatar: 'https://picsum.photos/seed/btc2/40/40',
        title: '本周日 06:00 (UTC+8) 比特币价格会落在哪个区间？',
        percentage: '24%',
        amount: '32,110',
        isFavorite: false,
        maxLeverage: '5X',
        maxReturn: '140%',
        timeRemaining: '12:03:27',
        participantCount: 2104,
        isTimeUrgent: false,
        options: [
            { text: '低于 85,000 USDT', percentage: '18%', yesCount: 523, noCount: 911 },
            { text: '85,000 - 92,000 USDT', percentage: '42%', yesCount: 1013, noCount: 763 },
            { text: '高于 92,000 USDT', percentage: '40%', yesCount: 568, noCount: 654 },
        ],
    },
    {
        id: 'defi-tvls',
        cardType: 'small',
        avatar: 'https://picsum.photos/seed/defi1/40/40',
        title: '一周内，以太坊 DeFi TVL 是否会重新站上 1,200 亿美金？',
        percentage: '29%',
        amount: '21,509',
        isFavorite: false,
        maxLeverage: '5X',
        maxReturn: '155%',
        timeRemaining: '3 天 05:22:51',
        participantCount: 1543,
        isTimeUrgent: false,
        options: [
            { text: '站上并维持至少 24 小时', percentage: '26%', yesCount: 412, noCount: 673 },
            { text: '触及后迅速回落', percentage: '38%', yesCount: 521, noCount: 498 },
        ],
    },
    {
        id: 'eth-etf-approval',
        cardType: 'large',
        avatar: 'https://picsum.photos/seed/eth1/40/40',
        title: '以太坊现货 ETF 会在 2025 年 Q1 获批吗？',
        percentage: '54%',
        amount: '143,920',
        yesCount: 3120,
        noCount: 2681,
        isFavorite: true,
        maxLeverage: '8X',
        maxReturn: '185%',
        timeRemaining: '18:27:03',
        participantCount: 5801,
        isTimeUrgent: false,
    },
    {
        id: 'sol-tvls',
        cardType: 'large',
        avatar: 'https://picsum.photos/seed/sol1/40/40',
        title: 'Solana 全链 TVL 会在 3 月突破 200 亿美金吗？',
        percentage: '41%',
        amount: '87,305',
        yesCount: 1763,
        noCount: 2510,
        isFavorite: false,
        maxLeverage: '12X',
        maxReturn: '260%',
        timeRemaining: '1 天 02:15:30',
        participantCount: 4273,
        isTimeUrgent: false,
    },
    {
        id: 'meme-top10',
        cardType: 'large',
        avatar: 'https://picsum.photos/seed/meme1/40/40',
        title: '前 10 大 Meme 币总市值会在本周新增 30% 以上吗？',
        percentage: '36%',
        amount: '59,842',
        yesCount: 932,
        noCount: 1650,
        isFavorite: false,
        maxLeverage: '15X',
        maxReturn: '320%',
        timeRemaining: '05:08:19',
        participantCount: 2735,
        isTimeUrgent: true,
    },
    {
        id: 'ai-token-index',
        cardType: 'large',
        avatar: 'https://picsum.photos/seed/ai1/40/40',
        title: 'AI 板块指数在接下来 7 天会跑赢 BTC 吗？',
        percentage: '61%',
        amount: '112,407',
        yesCount: 2987,
        noCount: 1894,
        isFavorite: true,
        maxLeverage: '6X',
        maxReturn: '165%',
        timeRemaining: '16:45:02',
        participantCount: 4881,
        isTimeUrgent: false,
    },
    {
        id: 'eth-gas-50',
        cardType: 'small',
        avatar: 'https://picsum.photos/seed/eth2/40/40',
        title: '明天晚高峰以太坊主网 Gas 是否会维持在 50 Gwei 以下？',
        percentage: '31%',
        amount: '12,480',
        isFavorite: false,
        maxLeverage: '4X',
        maxReturn: '120%',
        timeRemaining: '08:45:10',
        participantCount: 987,
        isTimeUrgent: true,
        options: [
            { text: '始终低于 50 Gwei', percentage: '27%', yesCount: 312, noCount: 514 },
            { text: '至少 1 小时高于 80 Gwei', percentage: '39%', yesCount: 401, noCount: 376 },
        ],
    },
    {
        id: 'sol-tps',
        cardType: 'small',
        avatar: 'https://picsum.photos/seed/sol2/40/40',
        title: '接下来 48 小时，Solana 主网 TPS 是否会连续 6 小时超过 3,000？',
        percentage: '19%',
        amount: '9,763',
        isFavorite: false,
        maxLeverage: '7X',
        maxReturn: '190%',
        timeRemaining: '22:11:09',
        participantCount: 654,
        isTimeUrgent: false,
        options: [
            { text: '会连续 6 小时以上', percentage: '21%', yesCount: 203, noCount: 321 },
            { text: '最多 3 小时', percentage: '34%', yesCount: 180, noCount: 276 },
        ],
    },
    {
        id: 'nft-volume',
        cardType: 'small',
        avatar: 'https://picsum.photos/seed/nft1/40/40',
        title: '本周 OpenSea + Blur 日均 NFT 交易量是否会超过上周 20%？',
        percentage: '22%',
        amount: '7,804',
        isFavorite: false,
        maxLeverage: '3X',
        maxReturn: '115%',
        timeRemaining: '1 天 11:09:33',
        participantCount: 832,
        isTimeUrgent: false,
        options: [
            { text: '增幅 ≥ 20%', percentage: '24%', yesCount: 210, noCount: 332 },
            { text: '变化在 ±10% 以内', percentage: '41%', yesCount: 356, noCount: 298 },
        ],
    },
];

// 兼容 PC 端首页：按卡片类型拆分为左右列表
export const leftList = cardList.filter((item) => item.cardType === 'large');
export const rightList = cardList.filter((item) => item.cardType === 'small');
